services:

  app:
    ports:
      - "80:80"
      - 5173:5173
    build: ../docker/app
    container_name: laravel_app
    volumes:
      - ../src:/var/www/html

  db:
    image: mysql:8.0
    container_name: laravel_db

    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      TZ: 'Asia/Tokyo'

    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ../docker/db/data:/var/lib/mysql
      - ../docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_pma
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions
